apiVersion: cdn.upjet-bunnynet.m.upbound.io/v1alpha1
kind: Hostname
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/hostname
  labels:
    testing.upbound.io/example-name: bunnynet
  name: bunnynet
  namespace: crossplane-system
spec:
  forProvider:
    forceSsl: false
    name: my-pullzone.b-cdn.net
    pullzone: ${bunnynet_pullzone.example.id}
