apiVersion: compute.upjet-bunnynet.upbound.io/v1alpha1
kind: ContainerImageregistry
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/containerimageregistry
  labels:
    testing.upbound.io/example-name: github
  name: github
spec:
  forProvider:
    registry: GitHub
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    username: my-github-username
