// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type OptimizerClassInitParameters struct {

	// The aspect ratio for image optimization.
	AspectRatio *string `json:"aspectRatio,omitempty" tf:"aspect_ratio,omitempty"`

	// Indicates whether automatic optimization for images is enabled.
	AutoOptimize *string `json:"autoOptimize,omitempty" tf:"auto_optimize,omitempty"`

	// The level of blur to apply to images.
	Blur *float64 `json:"blur,omitempty" tf:"blur,omitempty"`

	// The brightness adjustment for images.
	Brightness *float64 `json:"brightness,omitempty" tf:"brightness,omitempty"`

	// The contrast adjustment for images.
	Contrast *float64 `json:"contrast,omitempty" tf:"contrast,omitempty"`

	// The cropping settings for images.
	Crop *string `json:"crop,omitempty" tf:"crop,omitempty"`

	// The gravity setting for cropping.
	CropGravity *string `json:"cropGravity,omitempty" tf:"crop_gravity,omitempty"`

	// Indicates whether to flip images horizontally.
	Flip *bool `json:"flip,omitempty" tf:"flip,omitempty"`

	// Indicates whether to flip images vertically.
	Flop *bool `json:"flop,omitempty" tf:"flop,omitempty"`

	// The height to which images should be resized.
	Height *float64 `json:"height,omitempty" tf:"height,omitempty"`

	// The hue adjustment for images.
	Hue *float64 `json:"hue,omitempty" tf:"hue,omitempty"`

	// The name of the optimizer class.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pull zone.
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// The quality setting for image optimization.
	Quality *float64 `json:"quality,omitempty" tf:"quality,omitempty"`

	// The saturation adjustment for images.
	Saturation *float64 `json:"saturation,omitempty" tf:"saturation,omitempty"`

	// The level of sepia tone to apply to images.
	Sepia *float64 `json:"sepia,omitempty" tf:"sepia,omitempty"`

	// Indicates whether to sharpen images.
	Sharpen *bool `json:"sharpen,omitempty" tf:"sharpen,omitempty"`

	// The width to which images should be resized.
	Width *float64 `json:"width,omitempty" tf:"width,omitempty"`
}

type OptimizerClassObservation struct {

	// The aspect ratio for image optimization.
	AspectRatio *string `json:"aspectRatio,omitempty" tf:"aspect_ratio,omitempty"`

	// Indicates whether automatic optimization for images is enabled.
	AutoOptimize *string `json:"autoOptimize,omitempty" tf:"auto_optimize,omitempty"`

	// The level of blur to apply to images.
	Blur *float64 `json:"blur,omitempty" tf:"blur,omitempty"`

	// The brightness adjustment for images.
	Brightness *float64 `json:"brightness,omitempty" tf:"brightness,omitempty"`

	// The contrast adjustment for images.
	Contrast *float64 `json:"contrast,omitempty" tf:"contrast,omitempty"`

	// The cropping settings for images.
	Crop *string `json:"crop,omitempty" tf:"crop,omitempty"`

	// The gravity setting for cropping.
	CropGravity *string `json:"cropGravity,omitempty" tf:"crop_gravity,omitempty"`

	// Indicates whether to flip images horizontally.
	Flip *bool `json:"flip,omitempty" tf:"flip,omitempty"`

	// Indicates whether to flip images vertically.
	Flop *bool `json:"flop,omitempty" tf:"flop,omitempty"`

	// The height to which images should be resized.
	Height *float64 `json:"height,omitempty" tf:"height,omitempty"`

	// The hue adjustment for images.
	Hue *float64 `json:"hue,omitempty" tf:"hue,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the optimizer class.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pull zone.
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// The quality setting for image optimization.
	Quality *float64 `json:"quality,omitempty" tf:"quality,omitempty"`

	// The saturation adjustment for images.
	Saturation *float64 `json:"saturation,omitempty" tf:"saturation,omitempty"`

	// The level of sepia tone to apply to images.
	Sepia *float64 `json:"sepia,omitempty" tf:"sepia,omitempty"`

	// Indicates whether to sharpen images.
	Sharpen *bool `json:"sharpen,omitempty" tf:"sharpen,omitempty"`

	// The width to which images should be resized.
	Width *float64 `json:"width,omitempty" tf:"width,omitempty"`
}

type OptimizerClassParameters struct {

	// The aspect ratio for image optimization.
	// +kubebuilder:validation:Optional
	AspectRatio *string `json:"aspectRatio,omitempty" tf:"aspect_ratio,omitempty"`

	// Indicates whether automatic optimization for images is enabled.
	// +kubebuilder:validation:Optional
	AutoOptimize *string `json:"autoOptimize,omitempty" tf:"auto_optimize,omitempty"`

	// The level of blur to apply to images.
	// +kubebuilder:validation:Optional
	Blur *float64 `json:"blur,omitempty" tf:"blur,omitempty"`

	// The brightness adjustment for images.
	// +kubebuilder:validation:Optional
	Brightness *float64 `json:"brightness,omitempty" tf:"brightness,omitempty"`

	// The contrast adjustment for images.
	// +kubebuilder:validation:Optional
	Contrast *float64 `json:"contrast,omitempty" tf:"contrast,omitempty"`

	// The cropping settings for images.
	// +kubebuilder:validation:Optional
	Crop *string `json:"crop,omitempty" tf:"crop,omitempty"`

	// The gravity setting for cropping.
	// +kubebuilder:validation:Optional
	CropGravity *string `json:"cropGravity,omitempty" tf:"crop_gravity,omitempty"`

	// Indicates whether to flip images horizontally.
	// +kubebuilder:validation:Optional
	Flip *bool `json:"flip,omitempty" tf:"flip,omitempty"`

	// Indicates whether to flip images vertically.
	// +kubebuilder:validation:Optional
	Flop *bool `json:"flop,omitempty" tf:"flop,omitempty"`

	// The height to which images should be resized.
	// +kubebuilder:validation:Optional
	Height *float64 `json:"height,omitempty" tf:"height,omitempty"`

	// The hue adjustment for images.
	// +kubebuilder:validation:Optional
	Hue *float64 `json:"hue,omitempty" tf:"hue,omitempty"`

	// The name of the optimizer class.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pull zone.
	// +kubebuilder:validation:Optional
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// The quality setting for image optimization.
	// +kubebuilder:validation:Optional
	Quality *float64 `json:"quality,omitempty" tf:"quality,omitempty"`

	// The saturation adjustment for images.
	// +kubebuilder:validation:Optional
	Saturation *float64 `json:"saturation,omitempty" tf:"saturation,omitempty"`

	// The level of sepia tone to apply to images.
	// +kubebuilder:validation:Optional
	Sepia *float64 `json:"sepia,omitempty" tf:"sepia,omitempty"`

	// Indicates whether to sharpen images.
	// +kubebuilder:validation:Optional
	Sharpen *bool `json:"sharpen,omitempty" tf:"sharpen,omitempty"`

	// The width to which images should be resized.
	// +kubebuilder:validation:Optional
	Width *float64 `json:"width,omitempty" tf:"width,omitempty"`
}

// OptimizerClassSpec defines the desired state of OptimizerClass
type OptimizerClassSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OptimizerClassParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OptimizerClassInitParameters `json:"initProvider,omitempty"`
}

// OptimizerClassStatus defines the observed state of OptimizerClass.
type OptimizerClassStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OptimizerClassObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OptimizerClass is the Schema for the OptimizerClasss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-bunnynet}
type OptimizerClass struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pullzone) || (has(self.initProvider) && has(self.initProvider.pullzone))",message="spec.forProvider.pullzone is a required parameter"
	Spec   OptimizerClassSpec   `json:"spec"`
	Status OptimizerClassStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OptimizerClassList contains a list of OptimizerClasss
type OptimizerClassList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OptimizerClass `json:"items"`
}

// Repository type metadata.
var (
	OptimizerClass_Kind             = "OptimizerClass"
	OptimizerClass_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OptimizerClass_Kind}.String()
	OptimizerClass_KindAPIVersion   = OptimizerClass_Kind + "." + CRDGroupVersion.String()
	OptimizerClass_GroupVersionKind = CRDGroupVersion.WithKind(OptimizerClass_Kind)
)

func init() {
	SchemeBuilder.Register(&OptimizerClass{}, &OptimizerClassList{})
}
