// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConditionInitParameters struct {

	// Options: `BEGINSWITH`, `CONTAINS`, `CONTAINSWORD`, `DETECTSQLI`, `DETECTXSS`, `ENDSWITH`, `EQ`, `GE`, `GT`, `LE`, `LT`, `RX`, `STREQ`, `STRMATCH`, `WITHIN`
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// Options: `ARGS`, `ARGS_COMBINED_SIZE`, `ARGS_GET`, `ARGS_GET_NAMES`, `ARGS_POST`, `ARGS_POST_NAMES`, `FILES_NAMES`, `FINGERPRINT`, `GEO`, `QUERY_STRING`, `REMOTE_ADDR`, `REQUEST_BASENAME`, `REQUEST_BODY`, `REQUEST_COOKIES`, `REQUEST_COOKIES_NAMES`, `REQUEST_FILENAME`, `REQUEST_HEADERS`, `REQUEST_HEADERS_NAMES`, `REQUEST_LINE`, `REQUEST_METHOD`, `REQUEST_PROTOCOL`, `REQUEST_URI`, `REQUEST_URI_RAW`, `RESPONSE_BODY`, `RESPONSE_HEADERS`, `RESPONSE_STATUS`, `VERIFIED_BOT_CATEGORY`
	Variable *string `json:"variable,omitempty" tf:"variable,omitempty"`

	VariableValue *string `json:"variableValue,omitempty" tf:"variable_value,omitempty"`
}

type ConditionObservation struct {

	// Options: `BEGINSWITH`, `CONTAINS`, `CONTAINSWORD`, `DETECTSQLI`, `DETECTXSS`, `ENDSWITH`, `EQ`, `GE`, `GT`, `LE`, `LT`, `RX`, `STREQ`, `STRMATCH`, `WITHIN`
	Operator *string `json:"operator,omitempty" tf:"operator,omitempty"`

	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// Options: `ARGS`, `ARGS_COMBINED_SIZE`, `ARGS_GET`, `ARGS_GET_NAMES`, `ARGS_POST`, `ARGS_POST_NAMES`, `FILES_NAMES`, `FINGERPRINT`, `GEO`, `QUERY_STRING`, `REMOTE_ADDR`, `REQUEST_BASENAME`, `REQUEST_BODY`, `REQUEST_COOKIES`, `REQUEST_COOKIES_NAMES`, `REQUEST_FILENAME`, `REQUEST_HEADERS`, `REQUEST_HEADERS_NAMES`, `REQUEST_LINE`, `REQUEST_METHOD`, `REQUEST_PROTOCOL`, `REQUEST_URI`, `REQUEST_URI_RAW`, `RESPONSE_BODY`, `RESPONSE_HEADERS`, `RESPONSE_STATUS`, `VERIFIED_BOT_CATEGORY`
	Variable *string `json:"variable,omitempty" tf:"variable,omitempty"`

	VariableValue *string `json:"variableValue,omitempty" tf:"variable_value,omitempty"`
}

type ConditionParameters struct {

	// Options: `BEGINSWITH`, `CONTAINS`, `CONTAINSWORD`, `DETECTSQLI`, `DETECTXSS`, `ENDSWITH`, `EQ`, `GE`, `GT`, `LE`, `LT`, `RX`, `STREQ`, `STRMATCH`, `WITHIN`
	// +kubebuilder:validation:Optional
	Operator *string `json:"operator" tf:"operator,omitempty"`

	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`

	// Options: `ARGS`, `ARGS_COMBINED_SIZE`, `ARGS_GET`, `ARGS_GET_NAMES`, `ARGS_POST`, `ARGS_POST_NAMES`, `FILES_NAMES`, `FINGERPRINT`, `GEO`, `QUERY_STRING`, `REMOTE_ADDR`, `REQUEST_BASENAME`, `REQUEST_BODY`, `REQUEST_COOKIES`, `REQUEST_COOKIES_NAMES`, `REQUEST_FILENAME`, `REQUEST_HEADERS`, `REQUEST_HEADERS_NAMES`, `REQUEST_LINE`, `REQUEST_METHOD`, `REQUEST_PROTOCOL`, `REQUEST_URI`, `REQUEST_URI_RAW`, `RESPONSE_BODY`, `RESPONSE_HEADERS`, `RESPONSE_STATUS`, `VERIFIED_BOT_CATEGORY`
	// +kubebuilder:validation:Optional
	Variable *string `json:"variable" tf:"variable,omitempty"`

	// +kubebuilder:validation:Optional
	VariableValue *string `json:"variableValue,omitempty" tf:"variable_value,omitempty"`
}

type LimitInitParameters struct {

	// The interval, in seconds, to consider for to trigger the rate limit rule.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// The number of request within the interval to trigger the rate limit rule.
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`
}

type LimitObservation struct {

	// The interval, in seconds, to consider for to trigger the rate limit rule.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// The number of request within the interval to trigger the rate limit rule.
	Requests *float64 `json:"requests,omitempty" tf:"requests,omitempty"`
}

type LimitParameters struct {

	// The interval, in seconds, to consider for to trigger the rate limit rule.
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval" tf:"interval,omitempty"`

	// The number of request within the interval to trigger the rate limit rule.
	// +kubebuilder:validation:Optional
	Requests *float64 `json:"requests" tf:"requests,omitempty"`
}

type RatelimitRuleInitParameters struct {

	// The condition to trigger the rate limit rule.
	Condition []ConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// The rate limit rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The rate limit rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pullzone.
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// Options: `CMDLINE`, `COMPRESSWHITESPACE`, `CSSDECODE`, `HEXENCODE`, `HTMLENTITYDECODE`, `JSDECODE`, `LENGTH`, `LOWERCASE`, `MD5`, `NORMALISEPATH`, `NORMALISEPATHWIN`, `NORMALIZEPATH`, `NORMALIZEPATHWIN`, `REMOVECOMMENTS`, `REMOVENULLS`, `REMOVEWHITESPACE`, `REPLACECOMMENTS`, `SHA1`, `URLDECODE`, `URLDECODEUNI`, `UTF8TOUNICODE`
	// +listType=set
	Transformations []*string `json:"transformations,omitempty" tf:"transformations,omitempty"`
}

type RatelimitRuleObservation struct {

	// The condition to trigger the rate limit rule.
	Condition []ConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	// The rate limit rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Limit []LimitObservation `json:"limit,omitempty" tf:"limit,omitempty"`

	// The rate limit rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pullzone.
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// The response once the rate limit rule is triggered.
	Response []ResponseObservation `json:"response,omitempty" tf:"response,omitempty"`

	// Options: `CMDLINE`, `COMPRESSWHITESPACE`, `CSSDECODE`, `HEXENCODE`, `HTMLENTITYDECODE`, `JSDECODE`, `LENGTH`, `LOWERCASE`, `MD5`, `NORMALISEPATH`, `NORMALISEPATHWIN`, `NORMALIZEPATH`, `NORMALIZEPATHWIN`, `REMOVECOMMENTS`, `REMOVENULLS`, `REMOVEWHITESPACE`, `REPLACECOMMENTS`, `SHA1`, `URLDECODE`, `URLDECODEUNI`, `UTF8TOUNICODE`
	// +listType=set
	Transformations []*string `json:"transformations,omitempty" tf:"transformations,omitempty"`
}

type RatelimitRuleParameters struct {

	// The condition to trigger the rate limit rule.
	// +kubebuilder:validation:Optional
	Condition []ConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// The rate limit rule description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The rate limit rule name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the linked pullzone.
	// +kubebuilder:validation:Optional
	Pullzone *float64 `json:"pullzone,omitempty" tf:"pullzone,omitempty"`

	// Options: `CMDLINE`, `COMPRESSWHITESPACE`, `CSSDECODE`, `HEXENCODE`, `HTMLENTITYDECODE`, `JSDECODE`, `LENGTH`, `LOWERCASE`, `MD5`, `NORMALISEPATH`, `NORMALISEPATHWIN`, `NORMALIZEPATH`, `NORMALIZEPATHWIN`, `REMOVECOMMENTS`, `REMOVENULLS`, `REMOVEWHITESPACE`, `REPLACECOMMENTS`, `SHA1`, `URLDECODE`, `URLDECODEUNI`, `UTF8TOUNICODE`
	// +kubebuilder:validation:Optional
	// +listType=set
	Transformations []*string `json:"transformations,omitempty" tf:"transformations,omitempty"`
}

type ResponseInitParameters struct {

	// The interval, in seconds, that the rate limit will apply.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type ResponseObservation struct {

	// The interval, in seconds, that the rate limit will apply.
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`
}

type ResponseParameters struct {

	// The interval, in seconds, that the rate limit will apply.
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval" tf:"interval,omitempty"`
}

// RatelimitRuleSpec defines the desired state of RatelimitRule
type RatelimitRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RatelimitRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RatelimitRuleInitParameters `json:"initProvider,omitempty"`
}

// RatelimitRuleStatus defines the observed state of RatelimitRule.
type RatelimitRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RatelimitRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RatelimitRule is the Schema for the RatelimitRules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-bunnynet}
type RatelimitRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pullzone) || (has(self.initProvider) && has(self.initProvider.pullzone))",message="spec.forProvider.pullzone is a required parameter"
	Spec   RatelimitRuleSpec   `json:"spec"`
	Status RatelimitRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RatelimitRuleList contains a list of RatelimitRules
type RatelimitRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RatelimitRule `json:"items"`
}

// Repository type metadata.
var (
	RatelimitRule_Kind             = "RatelimitRule"
	RatelimitRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RatelimitRule_Kind}.String()
	RatelimitRule_KindAPIVersion   = RatelimitRule_Kind + "." + CRDGroupVersion.String()
	RatelimitRule_GroupVersionKind = CRDGroupVersion.WithKind(RatelimitRule_Kind)
)

func init() {
	SchemeBuilder.Register(&RatelimitRule{}, &RatelimitRuleList{})
}
