// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ChaptersInitParameters struct {

	// (String)
	End *string `json:"end,omitempty" tf:"end"`

	// (String)
	Start *string `json:"start,omitempty" tf:"start"`

	// (String) The title of the video.
	Title *string `json:"title,omitempty" tf:"title"`
}

type ChaptersObservation struct {

	// (String)
	End *string `json:"end,omitempty" tf:"end,omitempty"`

	// (String)
	Start *string `json:"start,omitempty" tf:"start,omitempty"`

	// (String) The title of the video.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type ChaptersParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	End *string `json:"end,omitempty" tf:"end"`

	// (String)
	// +kubebuilder:validation:Optional
	Start *string `json:"start,omitempty" tf:"start"`

	// (String) The title of the video.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title"`
}

type MomentsInitParameters struct {

	// (String)
	Label *string `json:"label,omitempty" tf:"label"`

	// (String)
	Timestamp *string `json:"timestamp,omitempty" tf:"timestamp"`
}

type MomentsObservation struct {

	// (String)
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// (String)
	Timestamp *string `json:"timestamp,omitempty" tf:"timestamp,omitempty"`
}

type MomentsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label"`

	// (String)
	// +kubebuilder:validation:Optional
	Timestamp *string `json:"timestamp,omitempty" tf:"timestamp"`
}

type VideoInitParameters struct {

	// (Set of Object) The list of chapters available in the video. (see below for nested schema)
	// The list of chapters available in the video.
	Chapters []ChaptersInitParameters `json:"chapters,omitempty" tf:"chapters,omitempty"`

	// (String) The ID of the collection to which the video belongs.
	// The ID of the collection to which the video belongs.
	Collection *string `json:"collection,omitempty" tf:"collection,omitempty"`

	// (String) The description of the video.
	// The description of the video.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The ID of the stream library to which the video belongs.
	// The ID of the stream library to which the video belongs.
	Library *float64 `json:"library,omitempty" tf:"library,omitempty"`

	// (Set of Object) The list of moments available in the video. (see below for nested schema)
	// The list of moments available in the video.
	Moments []MomentsInitParameters `json:"moments,omitempty" tf:"moments,omitempty"`

	// (String) The title of the video.
	// The title of the video.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type VideoObservation struct {

	// (Set of Object) The list of chapters available in the video. (see below for nested schema)
	// The list of chapters available in the video.
	Chapters []ChaptersObservation `json:"chapters,omitempty" tf:"chapters,omitempty"`

	// (String) The ID of the collection to which the video belongs.
	// The ID of the collection to which the video belongs.
	Collection *string `json:"collection,omitempty" tf:"collection,omitempty"`

	// (String) The description of the video.
	// The description of the video.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The unique ID of the video.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) The ID of the stream library to which the video belongs.
	// The ID of the stream library to which the video belongs.
	Library *float64 `json:"library,omitempty" tf:"library,omitempty"`

	// (Set of Object) The list of moments available in the video. (see below for nested schema)
	// The list of moments available in the video.
	Moments []MomentsObservation `json:"moments,omitempty" tf:"moments,omitempty"`

	// (String) The title of the video.
	// The title of the video.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type VideoParameters struct {

	// (Set of Object) The list of chapters available in the video. (see below for nested schema)
	// The list of chapters available in the video.
	// +kubebuilder:validation:Optional
	Chapters []ChaptersParameters `json:"chapters,omitempty" tf:"chapters,omitempty"`

	// (String) The ID of the collection to which the video belongs.
	// The ID of the collection to which the video belongs.
	// +kubebuilder:validation:Optional
	Collection *string `json:"collection,omitempty" tf:"collection,omitempty"`

	// (String) The description of the video.
	// The description of the video.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) The ID of the stream library to which the video belongs.
	// The ID of the stream library to which the video belongs.
	// +kubebuilder:validation:Optional
	Library *float64 `json:"library,omitempty" tf:"library,omitempty"`

	// (Set of Object) The list of moments available in the video. (see below for nested schema)
	// The list of moments available in the video.
	// +kubebuilder:validation:Optional
	Moments []MomentsParameters `json:"moments,omitempty" tf:"moments,omitempty"`

	// (String) The title of the video.
	// The title of the video.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// VideoSpec defines the desired state of Video
type VideoSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VideoParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VideoInitParameters `json:"initProvider,omitempty"`
}

// VideoStatus defines the observed state of Video.
type VideoStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VideoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Video is the Schema for the Videos API. This resource manages individual video files in bunny.net Stream. It is used to manage individual video files in a stream library.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-bunnynet}
type Video struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.library) || (has(self.initProvider) && has(self.initProvider.library))",message="spec.forProvider.library is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   VideoSpec   `json:"spec"`
	Status VideoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VideoList contains a list of Videos
type VideoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Video `json:"items"`
}

// Repository type metadata.
var (
	Video_Kind             = "Video"
	Video_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Video_Kind}.String()
	Video_KindAPIVersion   = Video_Kind + "." + CRDGroupVersion.String()
	Video_GroupVersionKind = CRDGroupVersion.WithKind(Video_Kind)
)

func init() {
	SchemeBuilder.Register(&Video{}, &VideoList{})
}
