// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CdnInitParameters struct {

	// Indicates whether the container will handle TLS termination.
	OriginSSL *bool `json:"originSsl,omitempty" tf:"origin_ssl,omitempty"`

	// Indicates whether sticky sessions is enabled.
	StickySessions []StickySessionsInitParameters `json:"stickySessions,omitempty" tf:"sticky_sessions,omitempty"`
}

type CdnObservation struct {

	// Indicates whether the container will handle TLS termination.
	OriginSSL *bool `json:"originSsl,omitempty" tf:"origin_ssl,omitempty"`

	// The ID of the pullzone associated with the endpoint.
	PullzoneID *float64 `json:"pullzoneId,omitempty" tf:"pullzone_id,omitempty"`

	// Indicates whether sticky sessions is enabled.
	StickySessions []StickySessionsObservation `json:"stickySessions,omitempty" tf:"sticky_sessions,omitempty"`
}

type CdnParameters struct {

	// Indicates whether the container will handle TLS termination.
	// +kubebuilder:validation:Optional
	OriginSSL *bool `json:"originSsl,omitempty" tf:"origin_ssl,omitempty"`

	// Indicates whether sticky sessions is enabled.
	// +kubebuilder:validation:Optional
	StickySessions []StickySessionsParameters `json:"stickySessions,omitempty" tf:"sticky_sessions,omitempty"`
}

type ContainerAppInitParameters struct {

	// The maximum number of instances that will be provisioned per active region.
	AutoscalingMax *float64 `json:"autoscalingMax,omitempty" tf:"autoscaling_max,omitempty"`

	// The minimum number of instances that will be provisioned per active region.
	AutoscalingMin *float64 `json:"autoscalingMin,omitempty" tf:"autoscaling_min,omitempty"`

	// Defines a container for the application.
	Container []ContainerInitParameters `json:"container,omitempty" tf:"container,omitempty"`

	// The name of the application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The regions that will be dynamically provisionable based on the user latency.
	// +listType=set
	RegionsAllowed []*string `json:"regionsAllowed,omitempty" tf:"regions_allowed,omitempty"`

	// The maximum amount of regions to be deployed at any given time.
	RegionsMaxAllowed *float64 `json:"regionsMaxAllowed,omitempty" tf:"regions_max_allowed,omitempty"`

	// The regions that will be statically provisioned and will always be running and available to users.
	// +listType=set
	RegionsRequired []*string `json:"regionsRequired,omitempty" tf:"regions_required,omitempty"`

	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`

	// Defines a persistent volume to be used by the application.
	Volume []VolumeInitParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ContainerAppObservation struct {

	// The maximum number of instances that will be provisioned per active region.
	AutoscalingMax *float64 `json:"autoscalingMax,omitempty" tf:"autoscaling_max,omitempty"`

	// The minimum number of instances that will be provisioned per active region.
	AutoscalingMin *float64 `json:"autoscalingMin,omitempty" tf:"autoscaling_min,omitempty"`

	// Defines a container for the application.
	Container []ContainerObservation `json:"container,omitempty" tf:"container,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The regions that will be dynamically provisionable based on the user latency.
	// +listType=set
	RegionsAllowed []*string `json:"regionsAllowed,omitempty" tf:"regions_allowed,omitempty"`

	// The maximum amount of regions to be deployed at any given time.
	RegionsMaxAllowed *float64 `json:"regionsMaxAllowed,omitempty" tf:"regions_max_allowed,omitempty"`

	// The regions that will be statically provisioned and will always be running and available to users.
	// +listType=set
	RegionsRequired []*string `json:"regionsRequired,omitempty" tf:"regions_required,omitempty"`

	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`

	// Defines a persistent volume to be used by the application.
	Volume []VolumeObservation `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ContainerAppParameters struct {

	// The maximum number of instances that will be provisioned per active region.
	// +kubebuilder:validation:Optional
	AutoscalingMax *float64 `json:"autoscalingMax,omitempty" tf:"autoscaling_max,omitempty"`

	// The minimum number of instances that will be provisioned per active region.
	// +kubebuilder:validation:Optional
	AutoscalingMin *float64 `json:"autoscalingMin,omitempty" tf:"autoscaling_min,omitempty"`

	// Defines a container for the application.
	// +kubebuilder:validation:Optional
	Container []ContainerParameters `json:"container,omitempty" tf:"container,omitempty"`

	// The name of the application.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The regions that will be dynamically provisionable based on the user latency.
	// +kubebuilder:validation:Optional
	// +listType=set
	RegionsAllowed []*string `json:"regionsAllowed,omitempty" tf:"regions_allowed,omitempty"`

	// The maximum amount of regions to be deployed at any given time.
	// +kubebuilder:validation:Optional
	RegionsMaxAllowed *float64 `json:"regionsMaxAllowed,omitempty" tf:"regions_max_allowed,omitempty"`

	// The regions that will be statically provisioned and will always be running and available to users.
	// +kubebuilder:validation:Optional
	// +listType=set
	RegionsRequired []*string `json:"regionsRequired,omitempty" tf:"regions_required,omitempty"`

	// +kubebuilder:validation:Optional
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`

	// Defines a persistent volume to be used by the application.
	// +kubebuilder:validation:Optional
	Volume []VolumeParameters `json:"volume,omitempty" tf:"volume,omitempty"`
}

type ContainerInitParameters struct {

	// The arguments that will be added to the container entry point when starting the image.
	Arguments *string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// A custom startup command that will execute once the container is launched.
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Defines a public endpoint for the application.
	Endpoint []EndpointInitParameters `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Defines an environment variable for the container
	Env []EnvInitParameters `json:"env,omitempty" tf:"env,omitempty"`

	// The image digest.
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The image name within the registry, without the domain prefix (i.e.: `my-app`).
	ImageName *string `json:"imageName,omitempty" tf:"image_name,omitempty"`

	// The image namespace within the registry, without the domain prefix (i.e.: `my-org`).
	ImageNamespace *string `json:"imageNamespace,omitempty" tf:"image_namespace,omitempty"`

	// Options: `Always`, `IfNotPresent`
	ImagePullPolicy *string `json:"imagePullPolicy,omitempty" tf:"image_pull_policy,omitempty"`

	// The image registry for the container.
	ImageRegistry *float64 `json:"imageRegistry,omitempty" tf:"image_registry,omitempty"`

	// The image tag (i.e.: `2.9-alpine`).
	ImageTag *string `json:"imageTag,omitempty" tf:"image_tag,omitempty"`

	// Checks that the application is actively running without issues. It the check fails, the container will be automatically restarted
	LivenessProbe []LivenessProbeInitParameters `json:"livenessProbe,omitempty" tf:"liveness_probe,omitempty"`

	// The name of the container.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Checks if the application is fully prepared to handle incoming requests. No requests will be routed to the application until this check is successful.
	ReadinessProbe []ReadinessProbeInitParameters `json:"readinessProbe,omitempty" tf:"readiness_probe,omitempty"`

	// Checks if the application has successfully started. No requests will be routed to the application until this check is successful.
	StartupProbe []StartupProbeInitParameters `json:"startupProbe,omitempty" tf:"startup_probe,omitempty"`

	// Mounts a volume within a container
	Volumemount []VolumemountInitParameters `json:"volumemount,omitempty" tf:"volumemount,omitempty"`

	// The working directory of the container runtime.
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type ContainerObservation struct {

	// The arguments that will be added to the container entry point when starting the image.
	Arguments *string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// A custom startup command that will execute once the container is launched.
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Defines a public endpoint for the application.
	Endpoint []EndpointObservation `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Defines an environment variable for the container
	Env []EnvObservation `json:"env,omitempty" tf:"env,omitempty"`

	// The unique identifier for the container.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The image digest.
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The image name within the registry, without the domain prefix (i.e.: `my-app`).
	ImageName *string `json:"imageName,omitempty" tf:"image_name,omitempty"`

	// The image namespace within the registry, without the domain prefix (i.e.: `my-org`).
	ImageNamespace *string `json:"imageNamespace,omitempty" tf:"image_namespace,omitempty"`

	// Options: `Always`, `IfNotPresent`
	ImagePullPolicy *string `json:"imagePullPolicy,omitempty" tf:"image_pull_policy,omitempty"`

	// The image registry for the container.
	ImageRegistry *float64 `json:"imageRegistry,omitempty" tf:"image_registry,omitempty"`

	// The image tag (i.e.: `2.9-alpine`).
	ImageTag *string `json:"imageTag,omitempty" tf:"image_tag,omitempty"`

	// Checks that the application is actively running without issues. It the check fails, the container will be automatically restarted
	LivenessProbe []LivenessProbeObservation `json:"livenessProbe,omitempty" tf:"liveness_probe,omitempty"`

	// The name of the container.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Checks if the application is fully prepared to handle incoming requests. No requests will be routed to the application until this check is successful.
	ReadinessProbe []ReadinessProbeObservation `json:"readinessProbe,omitempty" tf:"readiness_probe,omitempty"`

	// Checks if the application has successfully started. No requests will be routed to the application until this check is successful.
	StartupProbe []StartupProbeObservation `json:"startupProbe,omitempty" tf:"startup_probe,omitempty"`

	// Mounts a volume within a container
	Volumemount []VolumemountObservation `json:"volumemount,omitempty" tf:"volumemount,omitempty"`

	// The working directory of the container runtime.
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type ContainerParameters struct {

	// The arguments that will be added to the container entry point when starting the image.
	// +kubebuilder:validation:Optional
	Arguments *string `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// A custom startup command that will execute once the container is launched.
	// +kubebuilder:validation:Optional
	Command *string `json:"command,omitempty" tf:"command,omitempty"`

	// Defines a public endpoint for the application.
	// +kubebuilder:validation:Optional
	Endpoint []EndpointParameters `json:"endpoint,omitempty" tf:"endpoint,omitempty"`

	// Defines an environment variable for the container
	// +kubebuilder:validation:Optional
	Env []EnvParameters `json:"env,omitempty" tf:"env,omitempty"`

	// The image digest.
	// +kubebuilder:validation:Optional
	ImageDigest *string `json:"imageDigest,omitempty" tf:"image_digest,omitempty"`

	// The image name within the registry, without the domain prefix (i.e.: `my-app`).
	// +kubebuilder:validation:Optional
	ImageName *string `json:"imageName" tf:"image_name,omitempty"`

	// The image namespace within the registry, without the domain prefix (i.e.: `my-org`).
	// +kubebuilder:validation:Optional
	ImageNamespace *string `json:"imageNamespace" tf:"image_namespace,omitempty"`

	// Options: `Always`, `IfNotPresent`
	// +kubebuilder:validation:Optional
	ImagePullPolicy *string `json:"imagePullPolicy,omitempty" tf:"image_pull_policy,omitempty"`

	// The image registry for the container.
	// +kubebuilder:validation:Optional
	ImageRegistry *float64 `json:"imageRegistry" tf:"image_registry,omitempty"`

	// The image tag (i.e.: `2.9-alpine`).
	// +kubebuilder:validation:Optional
	ImageTag *string `json:"imageTag" tf:"image_tag,omitempty"`

	// Checks that the application is actively running without issues. It the check fails, the container will be automatically restarted
	// +kubebuilder:validation:Optional
	LivenessProbe []LivenessProbeParameters `json:"livenessProbe,omitempty" tf:"liveness_probe,omitempty"`

	// The name of the container.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Checks if the application is fully prepared to handle incoming requests. No requests will be routed to the application until this check is successful.
	// +kubebuilder:validation:Optional
	ReadinessProbe []ReadinessProbeParameters `json:"readinessProbe,omitempty" tf:"readiness_probe,omitempty"`

	// Checks if the application has successfully started. No requests will be routed to the application until this check is successful.
	// +kubebuilder:validation:Optional
	StartupProbe []StartupProbeParameters `json:"startupProbe,omitempty" tf:"startup_probe,omitempty"`

	// Mounts a volume within a container
	// +kubebuilder:validation:Optional
	Volumemount []VolumemountParameters `json:"volumemount,omitempty" tf:"volumemount,omitempty"`

	// The working directory of the container runtime.
	// +kubebuilder:validation:Optional
	WorkingDir *string `json:"workingDir,omitempty" tf:"working_dir,omitempty"`
}

type EndpointInitParameters struct {

	// Configurations for CDN endpoint.
	Cdn []CdnInitParameters `json:"cdn,omitempty" tf:"cdn,omitempty"`

	// The name of the endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Endpoint port configuration.
	Port []PortInitParameters `json:"port,omitempty" tf:"port,omitempty"`

	// Options: `Anycast`, `CDN`, `InternalIP`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EndpointObservation struct {

	// Configurations for CDN endpoint.
	Cdn []CdnObservation `json:"cdn,omitempty" tf:"cdn,omitempty"`

	// The name of the endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Endpoint port configuration.
	Port []PortObservation `json:"port,omitempty" tf:"port,omitempty"`

	// Options: `Anycast`, `CDN`, `InternalIP`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EndpointParameters struct {

	// Configurations for CDN endpoint.
	// +kubebuilder:validation:Optional
	Cdn []CdnParameters `json:"cdn,omitempty" tf:"cdn,omitempty"`

	// The name of the endpoint.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Endpoint port configuration.
	// +kubebuilder:validation:Optional
	Port []PortParameters `json:"port,omitempty" tf:"port,omitempty"`

	// Options: `Anycast`, `CDN`, `InternalIP`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type EnvInitParameters struct {

	// The name of the environment variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the environment variable.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EnvObservation struct {

	// The name of the environment variable.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The value of the environment variable.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EnvParameters struct {

	// The name of the environment variable.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The value of the environment variable.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type GRPCInitParameters struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type GRPCObservation struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type GRPCParameters struct {

	// The gRPC service name.
	// +kubebuilder:validation:Optional
	Service *string `json:"service" tf:"service,omitempty"`
}

type HTTPInitParameters struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type HTTPObservation struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type HTTPParameters struct {

	// The expected HTTP response status code.
	// +kubebuilder:validation:Optional
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

type LivenessProbeInitParameters struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []GRPCInitParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []HTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LivenessProbeObservation struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []GRPCObservation `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []HTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LivenessProbeParameters struct {

	// The number of failed probes to consider the container unhealthy.
	// +kubebuilder:validation:Optional
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	// +kubebuilder:validation:Optional
	GRPC []GRPCParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	// +kubebuilder:validation:Optional
	HTTP []HTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	// +kubebuilder:validation:Optional
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	// +kubebuilder:validation:Optional
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type PortInitParameters struct {

	// The container port number.
	Container *float64 `json:"container,omitempty" tf:"container,omitempty"`

	// The exposed port number.
	Exposed *float64 `json:"exposed,omitempty" tf:"exposed,omitempty"`

	// Options: `SCTP`, `TCP`, `UDP`
	// +listType=set
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`
}

type PortObservation struct {

	// The container port number.
	Container *float64 `json:"container,omitempty" tf:"container,omitempty"`

	// The exposed port number.
	Exposed *float64 `json:"exposed,omitempty" tf:"exposed,omitempty"`

	// Options: `SCTP`, `TCP`, `UDP`
	// +listType=set
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`
}

type PortParameters struct {

	// The container port number.
	// +kubebuilder:validation:Optional
	Container *float64 `json:"container" tf:"container,omitempty"`

	// The exposed port number.
	// +kubebuilder:validation:Optional
	Exposed *float64 `json:"exposed,omitempty" tf:"exposed,omitempty"`

	// Options: `SCTP`, `TCP`, `UDP`
	// +kubebuilder:validation:Optional
	// +listType=set
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`
}

type ReadinessProbeGRPCInitParameters struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type ReadinessProbeGRPCObservation struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type ReadinessProbeGRPCParameters struct {

	// The gRPC service name.
	// +kubebuilder:validation:Optional
	Service *string `json:"service" tf:"service,omitempty"`
}

type ReadinessProbeHTTPInitParameters struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type ReadinessProbeHTTPObservation struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type ReadinessProbeHTTPParameters struct {

	// The expected HTTP response status code.
	// +kubebuilder:validation:Optional
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

type ReadinessProbeInitParameters struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []ReadinessProbeGRPCInitParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []ReadinessProbeHTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReadinessProbeObservation struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []ReadinessProbeGRPCObservation `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []ReadinessProbeHTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReadinessProbeParameters struct {

	// The number of failed probes to consider the container unhealthy.
	// +kubebuilder:validation:Optional
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	// +kubebuilder:validation:Optional
	GRPC []ReadinessProbeGRPCParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	// +kubebuilder:validation:Optional
	HTTP []ReadinessProbeHTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	// +kubebuilder:validation:Optional
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	// +kubebuilder:validation:Optional
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type StartupProbeGRPCInitParameters struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type StartupProbeGRPCObservation struct {

	// The gRPC service name.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`
}

type StartupProbeGRPCParameters struct {

	// The gRPC service name.
	// +kubebuilder:validation:Optional
	Service *string `json:"service" tf:"service,omitempty"`
}

type StartupProbeHTTPInitParameters struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type StartupProbeHTTPObservation struct {

	// The expected HTTP response status code.
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type StartupProbeHTTPParameters struct {

	// The expected HTTP response status code.
	// +kubebuilder:validation:Optional
	ExpectedStatus *float64 `json:"expectedStatus,omitempty" tf:"expected_status,omitempty"`

	// The HTTP path to be requested.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

type StartupProbeInitParameters struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []StartupProbeGRPCInitParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []StartupProbeHTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StartupProbeObservation struct {

	// The number of failed probes to consider the container unhealthy.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	GRPC []StartupProbeGRPCObservation `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	HTTP []StartupProbeHTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StartupProbeParameters struct {

	// The number of failed probes to consider the container unhealthy.
	// +kubebuilder:validation:Optional
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// gRPC-specific configurations.
	// +kubebuilder:validation:Optional
	GRPC []StartupProbeGRPCParameters `json:"grpc,omitempty" tf:"grpc,omitempty"`

	// HTTP-specific configurations.
	// +kubebuilder:validation:Optional
	HTTP []StartupProbeHTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// The amount of time in seconds after the container is started to wait before the first probe is sent.
	// +kubebuilder:validation:Optional
	InitialDelay *float64 `json:"initialDelay,omitempty" tf:"initial_delay,omitempty"`

	// The amount of time in seconds between each probe.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// The port within the container the probe will connect to.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// The number of successful probes to consider the container healthy.
	// +kubebuilder:validation:Optional
	SuccessThreshold *float64 `json:"successThreshold,omitempty" tf:"success_threshold,omitempty"`

	// The amount of time in seconds the probe will wait for a response before considering it a failure.
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`

	// Options: `grpc`, `http`, `tcp`
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type StickySessionsInitParameters struct {

	// Incoming request headers used to select a pod for sticky sessions.
	// +listType=set
	Headers []*string `json:"headers,omitempty" tf:"headers,omitempty"`
}

type StickySessionsObservation struct {

	// Incoming request headers used to select a pod for sticky sessions.
	// +listType=set
	Headers []*string `json:"headers,omitempty" tf:"headers,omitempty"`
}

type StickySessionsParameters struct {

	// Incoming request headers used to select a pod for sticky sessions.
	// +kubebuilder:validation:Optional
	// +listType=set
	Headers []*string `json:"headers" tf:"headers,omitempty"`
}

type VolumeInitParameters struct {

	// The name of the volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The size of the volume, in Gigabytes (10^9 bytes).
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type VolumeObservation struct {

	// The name of the volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The size of the volume, in Gigabytes (10^9 bytes).
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type VolumeParameters struct {

	// The name of the volume.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The size of the volume, in Gigabytes (10^9 bytes).
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size" tf:"size,omitempty"`
}

type VolumemountInitParameters struct {

	// The name of the volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The path within the container where the volume will be mounted.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type VolumemountObservation struct {

	// The name of the volume.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The path within the container where the volume will be mounted.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type VolumemountParameters struct {

	// The name of the volume.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The path within the container where the volume will be mounted.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

// ContainerAppSpec defines the desired state of ContainerApp
type ContainerAppSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ContainerAppParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContainerAppInitParameters `json:"initProvider,omitempty"`
}

// ContainerAppStatus defines the observed state of ContainerApp.
type ContainerAppStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContainerAppObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContainerApp is the Schema for the ContainerApps API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-bunnynet}
type ContainerApp struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionsAllowed) || (has(self.initProvider) && has(self.initProvider.regionsAllowed))",message="spec.forProvider.regionsAllowed is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionsRequired) || (has(self.initProvider) && has(self.initProvider.regionsRequired))",message="spec.forProvider.regionsRequired is a required parameter"
	Spec   ContainerAppSpec   `json:"spec"`
	Status ContainerAppStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContainerAppList contains a list of ContainerApps
type ContainerAppList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContainerApp `json:"items"`
}

// Repository type metadata.
var (
	ContainerApp_Kind             = "ContainerApp"
	ContainerApp_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContainerApp_Kind}.String()
	ContainerApp_KindAPIVersion   = ContainerApp_Kind + "." + CRDGroupVersion.String()
	ContainerApp_GroupVersionKind = CRDGroupVersion.WithKind(ContainerApp_Kind)
)

func init() {
	SchemeBuilder.Register(&ContainerApp{}, &ContainerAppList{})
}
