// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ScriptSecretInitParameters struct {

	// The name of the secret.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the associated compute script.
	Script *float64 `json:"script,omitempty" tf:"script,omitempty"`

	// The value of the secret.
	ValueSecretRef v1.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`
}

type ScriptSecretObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the secret.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the associated compute script.
	Script *float64 `json:"script,omitempty" tf:"script,omitempty"`
}

type ScriptSecretParameters struct {

	// The name of the secret.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the associated compute script.
	// +kubebuilder:validation:Optional
	Script *float64 `json:"script,omitempty" tf:"script,omitempty"`

	// The value of the secret.
	// +kubebuilder:validation:Optional
	ValueSecretRef v1.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`
}

// ScriptSecretSpec defines the desired state of ScriptSecret
type ScriptSecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScriptSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScriptSecretInitParameters `json:"initProvider,omitempty"`
}

// ScriptSecretStatus defines the observed state of ScriptSecret.
type ScriptSecretStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScriptSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScriptSecret is the Schema for the ScriptSecrets API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-bunnynet}
type ScriptSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.script) || (has(self.initProvider) && has(self.initProvider.script))",message="spec.forProvider.script is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueSecretRef)",message="spec.forProvider.valueSecretRef is a required parameter"
	Spec   ScriptSecretSpec   `json:"spec"`
	Status ScriptSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScriptSecretList contains a list of ScriptSecrets
type ScriptSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScriptSecret `json:"items"`
}

// Repository type metadata.
var (
	ScriptSecret_Kind             = "ScriptSecret"
	ScriptSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScriptSecret_Kind}.String()
	ScriptSecret_KindAPIVersion   = ScriptSecret_Kind + "." + CRDGroupVersion.String()
	ScriptSecret_GroupVersionKind = CRDGroupVersion.WithKind(ScriptSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&ScriptSecret{}, &ScriptSecretList{})
}
