// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccessList) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Edgerule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Hostname) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OptimizerClass) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Pullzone) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RatelimitRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Shield) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WafRule) Hub() {}
