apiVersion: cdn.upjet-bunnynet.upbound.io/v1alpha1
kind: RatelimitRule
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/ratelimitrule
  labels:
    testing.upbound.io/example-name: wplogin
  name: wplogin
spec:
  forProvider:
    condition:
    - operator: BEGINSWITH
      value: /wp-login.php
      variable: REQUEST_URI
    description: WordPress Login
    name: WordPress Login
    pullzone: ${bunnynet_pullzone.test.id}
    transformations:
    - LOWERCASE
    - NORMALIZEPATH
    - URLDECODE
