//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaptersInitParameters) DeepCopyInto(out *ChaptersInitParameters) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaptersInitParameters.
func (in *ChaptersInitParameters) DeepCopy() *ChaptersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ChaptersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaptersObservation) DeepCopyInto(out *ChaptersObservation) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaptersObservation.
func (in *ChaptersObservation) DeepCopy() *ChaptersObservation {
	if in == nil {
		return nil
	}
	out := new(ChaptersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaptersParameters) DeepCopyInto(out *ChaptersParameters) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaptersParameters.
func (in *ChaptersParameters) DeepCopy() *ChaptersParameters {
	if in == nil {
		return nil
	}
	out := new(ChaptersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Collection) DeepCopyInto(out *Collection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Collection.
func (in *Collection) DeepCopy() *Collection {
	if in == nil {
		return nil
	}
	out := new(Collection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Collection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionInitParameters) DeepCopyInto(out *CollectionInitParameters) {
	*out = *in
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionInitParameters.
func (in *CollectionInitParameters) DeepCopy() *CollectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(CollectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionList) DeepCopyInto(out *CollectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Collection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionList.
func (in *CollectionList) DeepCopy() *CollectionList {
	if in == nil {
		return nil
	}
	out := new(CollectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionObservation) DeepCopyInto(out *CollectionObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionObservation.
func (in *CollectionObservation) DeepCopy() *CollectionObservation {
	if in == nil {
		return nil
	}
	out := new(CollectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionParameters) DeepCopyInto(out *CollectionParameters) {
	*out = *in
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionParameters.
func (in *CollectionParameters) DeepCopy() *CollectionParameters {
	if in == nil {
		return nil
	}
	out := new(CollectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionSpec) DeepCopyInto(out *CollectionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionSpec.
func (in *CollectionSpec) DeepCopy() *CollectionSpec {
	if in == nil {
		return nil
	}
	out := new(CollectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionStatus) DeepCopyInto(out *CollectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionStatus.
func (in *CollectionStatus) DeepCopy() *CollectionStatus {
	if in == nil {
		return nil
	}
	out := new(CollectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Library) DeepCopyInto(out *Library) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Library.
func (in *Library) DeepCopy() *Library {
	if in == nil {
		return nil
	}
	out := new(Library)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Library) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryInitParameters) DeepCopyInto(out *LibraryInitParameters) {
	*out = *in
	if in.Bitrate1080P != nil {
		in, out := &in.Bitrate1080P, &out.Bitrate1080P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate1440P != nil {
		in, out := &in.Bitrate1440P, &out.Bitrate1440P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate2160P != nil {
		in, out := &in.Bitrate2160P, &out.Bitrate2160P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate240P != nil {
		in, out := &in.Bitrate240P, &out.Bitrate240P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate360P != nil {
		in, out := &in.Bitrate360P, &out.Bitrate360P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate480P != nil {
		in, out := &in.Bitrate480P, &out.Bitrate480P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate720P != nil {
		in, out := &in.Bitrate720P, &out.Bitrate720P
		*out = new(float64)
		**out = **in
	}
	if in.CdnTokenAuthenticationRequired != nil {
		in, out := &in.CdnTokenAuthenticationRequired, &out.CdnTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.ContentTaggingEnabled != nil {
		in, out := &in.ContentTaggingEnabled, &out.ContentTaggingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectPlayEnabled != nil {
		in, out := &in.DirectPlayEnabled, &out.DirectPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectURLFileAccessBlocked != nil {
		in, out := &in.DirectURLFileAccessBlocked, &out.DirectURLFileAccessBlocked
		*out = new(bool)
		**out = **in
	}
	if in.DrmMediacageBasicEnabled != nil {
		in, out := &in.DrmMediacageBasicEnabled, &out.DrmMediacageBasicEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EarlyPlayEnabled != nil {
		in, out := &in.EarlyPlayEnabled, &out.EarlyPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EncodingTier != nil {
		in, out := &in.EncodingTier, &out.EncodingTier
		*out = new(string)
		**out = **in
	}
	if in.JitEncoding != nil {
		in, out := &in.JitEncoding, &out.JitEncoding
		*out = new(bool)
		**out = **in
	}
	if in.Mp4FallbackEnabled != nil {
		in, out := &in.Mp4FallbackEnabled, &out.Mp4FallbackEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MultiAudioTrackSupportEnabled != nil {
		in, out := &in.MultiAudioTrackSupportEnabled, &out.MultiAudioTrackSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalFilesKeep != nil {
		in, out := &in.OriginalFilesKeep, &out.OriginalFilesKeep
		*out = new(bool)
		**out = **in
	}
	if in.OutputCodecs != nil {
		in, out := &in.OutputCodecs, &out.OutputCodecs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCaptionsBackgroundColor != nil {
		in, out := &in.PlayerCaptionsBackgroundColor, &out.PlayerCaptionsBackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontColor != nil {
		in, out := &in.PlayerCaptionsFontColor, &out.PlayerCaptionsFontColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontSize != nil {
		in, out := &in.PlayerCaptionsFontSize, &out.PlayerCaptionsFontSize
		*out = new(float64)
		**out = **in
	}
	if in.PlayerControls != nil {
		in, out := &in.PlayerControls, &out.PlayerControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCustomHead != nil {
		in, out := &in.PlayerCustomHead, &out.PlayerCustomHead
		*out = new(string)
		**out = **in
	}
	if in.PlayerFontFamily != nil {
		in, out := &in.PlayerFontFamily, &out.PlayerFontFamily
		*out = new(string)
		**out = **in
	}
	if in.PlayerLanguage != nil {
		in, out := &in.PlayerLanguage, &out.PlayerLanguage
		*out = new(string)
		**out = **in
	}
	if in.PlayerPrimaryColor != nil {
		in, out := &in.PlayerPrimaryColor, &out.PlayerPrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerVersion != nil {
		in, out := &in.PlayerVersion, &out.PlayerVersion
		*out = new(float64)
		**out = **in
	}
	if in.PlayerWatchtimeHeatmapEnabled != nil {
		in, out := &in.PlayerWatchtimeHeatmapEnabled, &out.PlayerWatchtimeHeatmapEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ReferersAllowed != nil {
		in, out := &in.ReferersAllowed, &out.ReferersAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReferersBlocked != nil {
		in, out := &in.ReferersBlocked, &out.ReferersBlocked
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Resolutions != nil {
		in, out := &in.Resolutions, &out.Resolutions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TranscribingEnabled != nil {
		in, out := &in.TranscribingEnabled, &out.TranscribingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingLanguages != nil {
		in, out := &in.TranscribingLanguages, &out.TranscribingLanguages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TranscribingSmartDescriptionEnabled != nil {
		in, out := &in.TranscribingSmartDescriptionEnabled, &out.TranscribingSmartDescriptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingSmartTitleEnabled != nil {
		in, out := &in.TranscribingSmartTitleEnabled, &out.TranscribingSmartTitleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VastTagURL != nil {
		in, out := &in.VastTagURL, &out.VastTagURL
		*out = new(string)
		**out = **in
	}
	if in.ViewTokenAuthenticationRequired != nil {
		in, out := &in.ViewTokenAuthenticationRequired, &out.ViewTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.WatermarkHeight != nil {
		in, out := &in.WatermarkHeight, &out.WatermarkHeight
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionLeft != nil {
		in, out := &in.WatermarkPositionLeft, &out.WatermarkPositionLeft
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionTop != nil {
		in, out := &in.WatermarkPositionTop, &out.WatermarkPositionTop
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkWidth != nil {
		in, out := &in.WatermarkWidth, &out.WatermarkWidth
		*out = new(float64)
		**out = **in
	}
	if in.WebhookURL != nil {
		in, out := &in.WebhookURL, &out.WebhookURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryInitParameters.
func (in *LibraryInitParameters) DeepCopy() *LibraryInitParameters {
	if in == nil {
		return nil
	}
	out := new(LibraryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryList) DeepCopyInto(out *LibraryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Library, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryList.
func (in *LibraryList) DeepCopy() *LibraryList {
	if in == nil {
		return nil
	}
	out := new(LibraryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LibraryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryObservation) DeepCopyInto(out *LibraryObservation) {
	*out = *in
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(string)
		**out = **in
	}
	if in.Bitrate1080P != nil {
		in, out := &in.Bitrate1080P, &out.Bitrate1080P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate1440P != nil {
		in, out := &in.Bitrate1440P, &out.Bitrate1440P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate2160P != nil {
		in, out := &in.Bitrate2160P, &out.Bitrate2160P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate240P != nil {
		in, out := &in.Bitrate240P, &out.Bitrate240P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate360P != nil {
		in, out := &in.Bitrate360P, &out.Bitrate360P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate480P != nil {
		in, out := &in.Bitrate480P, &out.Bitrate480P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate720P != nil {
		in, out := &in.Bitrate720P, &out.Bitrate720P
		*out = new(float64)
		**out = **in
	}
	if in.CdnTokenAuthenticationRequired != nil {
		in, out := &in.CdnTokenAuthenticationRequired, &out.CdnTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.ContentTaggingEnabled != nil {
		in, out := &in.ContentTaggingEnabled, &out.ContentTaggingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectPlayEnabled != nil {
		in, out := &in.DirectPlayEnabled, &out.DirectPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectURLFileAccessBlocked != nil {
		in, out := &in.DirectURLFileAccessBlocked, &out.DirectURLFileAccessBlocked
		*out = new(bool)
		**out = **in
	}
	if in.DrmMediacageBasicEnabled != nil {
		in, out := &in.DrmMediacageBasicEnabled, &out.DrmMediacageBasicEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EarlyPlayEnabled != nil {
		in, out := &in.EarlyPlayEnabled, &out.EarlyPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EncodingTier != nil {
		in, out := &in.EncodingTier, &out.EncodingTier
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.JitEncoding != nil {
		in, out := &in.JitEncoding, &out.JitEncoding
		*out = new(bool)
		**out = **in
	}
	if in.Mp4FallbackEnabled != nil {
		in, out := &in.Mp4FallbackEnabled, &out.Mp4FallbackEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MultiAudioTrackSupportEnabled != nil {
		in, out := &in.MultiAudioTrackSupportEnabled, &out.MultiAudioTrackSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalFilesKeep != nil {
		in, out := &in.OriginalFilesKeep, &out.OriginalFilesKeep
		*out = new(bool)
		**out = **in
	}
	if in.OutputCodecs != nil {
		in, out := &in.OutputCodecs, &out.OutputCodecs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCaptionsBackgroundColor != nil {
		in, out := &in.PlayerCaptionsBackgroundColor, &out.PlayerCaptionsBackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontColor != nil {
		in, out := &in.PlayerCaptionsFontColor, &out.PlayerCaptionsFontColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontSize != nil {
		in, out := &in.PlayerCaptionsFontSize, &out.PlayerCaptionsFontSize
		*out = new(float64)
		**out = **in
	}
	if in.PlayerControls != nil {
		in, out := &in.PlayerControls, &out.PlayerControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCustomHead != nil {
		in, out := &in.PlayerCustomHead, &out.PlayerCustomHead
		*out = new(string)
		**out = **in
	}
	if in.PlayerFontFamily != nil {
		in, out := &in.PlayerFontFamily, &out.PlayerFontFamily
		*out = new(string)
		**out = **in
	}
	if in.PlayerLanguage != nil {
		in, out := &in.PlayerLanguage, &out.PlayerLanguage
		*out = new(string)
		**out = **in
	}
	if in.PlayerPrimaryColor != nil {
		in, out := &in.PlayerPrimaryColor, &out.PlayerPrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerVersion != nil {
		in, out := &in.PlayerVersion, &out.PlayerVersion
		*out = new(float64)
		**out = **in
	}
	if in.PlayerWatchtimeHeatmapEnabled != nil {
		in, out := &in.PlayerWatchtimeHeatmapEnabled, &out.PlayerWatchtimeHeatmapEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Pullzone != nil {
		in, out := &in.Pullzone, &out.Pullzone
		*out = new(float64)
		**out = **in
	}
	if in.ReferersAllowed != nil {
		in, out := &in.ReferersAllowed, &out.ReferersAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReferersBlocked != nil {
		in, out := &in.ReferersBlocked, &out.ReferersBlocked
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Resolutions != nil {
		in, out := &in.Resolutions, &out.Resolutions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StorageZone != nil {
		in, out := &in.StorageZone, &out.StorageZone
		*out = new(float64)
		**out = **in
	}
	if in.TranscribingEnabled != nil {
		in, out := &in.TranscribingEnabled, &out.TranscribingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingLanguages != nil {
		in, out := &in.TranscribingLanguages, &out.TranscribingLanguages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TranscribingSmartDescriptionEnabled != nil {
		in, out := &in.TranscribingSmartDescriptionEnabled, &out.TranscribingSmartDescriptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingSmartTitleEnabled != nil {
		in, out := &in.TranscribingSmartTitleEnabled, &out.TranscribingSmartTitleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VastTagURL != nil {
		in, out := &in.VastTagURL, &out.VastTagURL
		*out = new(string)
		**out = **in
	}
	if in.ViewTokenAuthenticationRequired != nil {
		in, out := &in.ViewTokenAuthenticationRequired, &out.ViewTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.WatermarkHeight != nil {
		in, out := &in.WatermarkHeight, &out.WatermarkHeight
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionLeft != nil {
		in, out := &in.WatermarkPositionLeft, &out.WatermarkPositionLeft
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionTop != nil {
		in, out := &in.WatermarkPositionTop, &out.WatermarkPositionTop
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkWidth != nil {
		in, out := &in.WatermarkWidth, &out.WatermarkWidth
		*out = new(float64)
		**out = **in
	}
	if in.WebhookURL != nil {
		in, out := &in.WebhookURL, &out.WebhookURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryObservation.
func (in *LibraryObservation) DeepCopy() *LibraryObservation {
	if in == nil {
		return nil
	}
	out := new(LibraryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryParameters) DeepCopyInto(out *LibraryParameters) {
	*out = *in
	if in.Bitrate1080P != nil {
		in, out := &in.Bitrate1080P, &out.Bitrate1080P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate1440P != nil {
		in, out := &in.Bitrate1440P, &out.Bitrate1440P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate2160P != nil {
		in, out := &in.Bitrate2160P, &out.Bitrate2160P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate240P != nil {
		in, out := &in.Bitrate240P, &out.Bitrate240P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate360P != nil {
		in, out := &in.Bitrate360P, &out.Bitrate360P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate480P != nil {
		in, out := &in.Bitrate480P, &out.Bitrate480P
		*out = new(float64)
		**out = **in
	}
	if in.Bitrate720P != nil {
		in, out := &in.Bitrate720P, &out.Bitrate720P
		*out = new(float64)
		**out = **in
	}
	if in.CdnTokenAuthenticationRequired != nil {
		in, out := &in.CdnTokenAuthenticationRequired, &out.CdnTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.ContentTaggingEnabled != nil {
		in, out := &in.ContentTaggingEnabled, &out.ContentTaggingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectPlayEnabled != nil {
		in, out := &in.DirectPlayEnabled, &out.DirectPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectURLFileAccessBlocked != nil {
		in, out := &in.DirectURLFileAccessBlocked, &out.DirectURLFileAccessBlocked
		*out = new(bool)
		**out = **in
	}
	if in.DrmMediacageBasicEnabled != nil {
		in, out := &in.DrmMediacageBasicEnabled, &out.DrmMediacageBasicEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EarlyPlayEnabled != nil {
		in, out := &in.EarlyPlayEnabled, &out.EarlyPlayEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EncodingTier != nil {
		in, out := &in.EncodingTier, &out.EncodingTier
		*out = new(string)
		**out = **in
	}
	if in.JitEncoding != nil {
		in, out := &in.JitEncoding, &out.JitEncoding
		*out = new(bool)
		**out = **in
	}
	if in.Mp4FallbackEnabled != nil {
		in, out := &in.Mp4FallbackEnabled, &out.Mp4FallbackEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MultiAudioTrackSupportEnabled != nil {
		in, out := &in.MultiAudioTrackSupportEnabled, &out.MultiAudioTrackSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OriginalFilesKeep != nil {
		in, out := &in.OriginalFilesKeep, &out.OriginalFilesKeep
		*out = new(bool)
		**out = **in
	}
	if in.OutputCodecs != nil {
		in, out := &in.OutputCodecs, &out.OutputCodecs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCaptionsBackgroundColor != nil {
		in, out := &in.PlayerCaptionsBackgroundColor, &out.PlayerCaptionsBackgroundColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontColor != nil {
		in, out := &in.PlayerCaptionsFontColor, &out.PlayerCaptionsFontColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerCaptionsFontSize != nil {
		in, out := &in.PlayerCaptionsFontSize, &out.PlayerCaptionsFontSize
		*out = new(float64)
		**out = **in
	}
	if in.PlayerControls != nil {
		in, out := &in.PlayerControls, &out.PlayerControls
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PlayerCustomHead != nil {
		in, out := &in.PlayerCustomHead, &out.PlayerCustomHead
		*out = new(string)
		**out = **in
	}
	if in.PlayerFontFamily != nil {
		in, out := &in.PlayerFontFamily, &out.PlayerFontFamily
		*out = new(string)
		**out = **in
	}
	if in.PlayerLanguage != nil {
		in, out := &in.PlayerLanguage, &out.PlayerLanguage
		*out = new(string)
		**out = **in
	}
	if in.PlayerPrimaryColor != nil {
		in, out := &in.PlayerPrimaryColor, &out.PlayerPrimaryColor
		*out = new(string)
		**out = **in
	}
	if in.PlayerVersion != nil {
		in, out := &in.PlayerVersion, &out.PlayerVersion
		*out = new(float64)
		**out = **in
	}
	if in.PlayerWatchtimeHeatmapEnabled != nil {
		in, out := &in.PlayerWatchtimeHeatmapEnabled, &out.PlayerWatchtimeHeatmapEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ReferersAllowed != nil {
		in, out := &in.ReferersAllowed, &out.ReferersAllowed
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReferersBlocked != nil {
		in, out := &in.ReferersBlocked, &out.ReferersBlocked
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Resolutions != nil {
		in, out := &in.Resolutions, &out.Resolutions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TranscribingEnabled != nil {
		in, out := &in.TranscribingEnabled, &out.TranscribingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingLanguages != nil {
		in, out := &in.TranscribingLanguages, &out.TranscribingLanguages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TranscribingSmartDescriptionEnabled != nil {
		in, out := &in.TranscribingSmartDescriptionEnabled, &out.TranscribingSmartDescriptionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TranscribingSmartTitleEnabled != nil {
		in, out := &in.TranscribingSmartTitleEnabled, &out.TranscribingSmartTitleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VastTagURL != nil {
		in, out := &in.VastTagURL, &out.VastTagURL
		*out = new(string)
		**out = **in
	}
	if in.ViewTokenAuthenticationRequired != nil {
		in, out := &in.ViewTokenAuthenticationRequired, &out.ViewTokenAuthenticationRequired
		*out = new(bool)
		**out = **in
	}
	if in.WatermarkHeight != nil {
		in, out := &in.WatermarkHeight, &out.WatermarkHeight
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionLeft != nil {
		in, out := &in.WatermarkPositionLeft, &out.WatermarkPositionLeft
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkPositionTop != nil {
		in, out := &in.WatermarkPositionTop, &out.WatermarkPositionTop
		*out = new(float64)
		**out = **in
	}
	if in.WatermarkWidth != nil {
		in, out := &in.WatermarkWidth, &out.WatermarkWidth
		*out = new(float64)
		**out = **in
	}
	if in.WebhookURL != nil {
		in, out := &in.WebhookURL, &out.WebhookURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryParameters.
func (in *LibraryParameters) DeepCopy() *LibraryParameters {
	if in == nil {
		return nil
	}
	out := new(LibraryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibrarySpec) DeepCopyInto(out *LibrarySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibrarySpec.
func (in *LibrarySpec) DeepCopy() *LibrarySpec {
	if in == nil {
		return nil
	}
	out := new(LibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryStatus) DeepCopyInto(out *LibraryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryStatus.
func (in *LibraryStatus) DeepCopy() *LibraryStatus {
	if in == nil {
		return nil
	}
	out := new(LibraryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MomentsInitParameters) DeepCopyInto(out *MomentsInitParameters) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MomentsInitParameters.
func (in *MomentsInitParameters) DeepCopy() *MomentsInitParameters {
	if in == nil {
		return nil
	}
	out := new(MomentsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MomentsObservation) DeepCopyInto(out *MomentsObservation) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MomentsObservation.
func (in *MomentsObservation) DeepCopy() *MomentsObservation {
	if in == nil {
		return nil
	}
	out := new(MomentsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MomentsParameters) DeepCopyInto(out *MomentsParameters) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MomentsParameters.
func (in *MomentsParameters) DeepCopy() *MomentsParameters {
	if in == nil {
		return nil
	}
	out := new(MomentsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Video) DeepCopyInto(out *Video) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Video.
func (in *Video) DeepCopy() *Video {
	if in == nil {
		return nil
	}
	out := new(Video)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Video) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoInitParameters) DeepCopyInto(out *VideoInitParameters) {
	*out = *in
	if in.Chapters != nil {
		in, out := &in.Chapters, &out.Chapters
		*out = make([]ChaptersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Moments != nil {
		in, out := &in.Moments, &out.Moments
		*out = make([]MomentsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoInitParameters.
func (in *VideoInitParameters) DeepCopy() *VideoInitParameters {
	if in == nil {
		return nil
	}
	out := new(VideoInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoList) DeepCopyInto(out *VideoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Video, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoList.
func (in *VideoList) DeepCopy() *VideoList {
	if in == nil {
		return nil
	}
	out := new(VideoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VideoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoObservation) DeepCopyInto(out *VideoObservation) {
	*out = *in
	if in.Chapters != nil {
		in, out := &in.Chapters, &out.Chapters
		*out = make([]ChaptersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Moments != nil {
		in, out := &in.Moments, &out.Moments
		*out = make([]MomentsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoObservation.
func (in *VideoObservation) DeepCopy() *VideoObservation {
	if in == nil {
		return nil
	}
	out := new(VideoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoParameters) DeepCopyInto(out *VideoParameters) {
	*out = *in
	if in.Chapters != nil {
		in, out := &in.Chapters, &out.Chapters
		*out = make([]ChaptersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(float64)
		**out = **in
	}
	if in.Moments != nil {
		in, out := &in.Moments, &out.Moments
		*out = make([]MomentsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoParameters.
func (in *VideoParameters) DeepCopy() *VideoParameters {
	if in == nil {
		return nil
	}
	out := new(VideoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoSpec) DeepCopyInto(out *VideoSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoSpec.
func (in *VideoSpec) DeepCopy() *VideoSpec {
	if in == nil {
		return nil
	}
	out := new(VideoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoStatus) DeepCopyInto(out *VideoStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoStatus.
func (in *VideoStatus) DeepCopy() *VideoStatus {
	if in == nil {
		return nil
	}
	out := new(VideoStatus)
	in.DeepCopyInto(out)
	return out
}
