apiVersion: account.upjet-bunnynet.m.upbound.io/v1alpha1
kind: Subuser
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/subuser
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    email: john@example.com
    firstname: John
    lastname: Doe
    passwordSecretRef:
      key: attribute.result
      name: example-password
    permissions:
    - zones
    - billing
