apiVersion: compute.upjet-bunnynet.m.upbound.io/v1alpha1
kind: ScriptSecret
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/scriptsecret
  labels:
    testing.upbound.io/example-name: APP_SECRET
  name: app-secret
  namespace: crossplane-system
spec:
  forProvider:
    name: APP_ENV
    script: ${bunnynet_compute_script.test.id}
    valueSecretRef:
      key: example-key
      name: example-secret
