apiVersion: storage.upjet-bunnynet.upbound.io/v1alpha1
kind: Zone
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1alpha1/zone
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: my-storage
    region: DE
    zoneTier: Standard
