// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FileInitParameters struct {

	// (String) The to be stored in the file. Use source to upload files from the local disk.
	// The to be stored in the file. Use <code>source</code> to upload files from the local disk.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Specifies the content type of the file.
	// Specifies the content type of the file.
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// (String) The path of the file within the storage zone.
	// The path of the file within the storage zone.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The path in the local disk for the file to be uploaded to the storage zone. Use content to define the content directly.
	// The path in the local disk for the file to be uploaded to the storage zone. Use <code>content</code> to define the content directly.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (Number) The ID of the storage zone where the file is stored.
	// The ID of the storage zone where the file is stored.
	Zone *float64 `json:"zone,omitempty" tf:"zone,omitempty"`
}

type FileObservation struct {

	// 256 hash of the stored file.
	// The SHA-256 hash of the stored file.
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (String) The to be stored in the file. Use source to upload files from the local disk.
	// The to be stored in the file. Use <code>source</code> to upload files from the local disk.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Specifies the content type of the file.
	// Specifies the content type of the file.
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// (String) The date and time when the file was created.
	// The date and time when the file was created.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// (String) The date and time when the file was last modified.
	// The date and time when the file was last modified.
	DateModified *string `json:"dateModified,omitempty" tf:"date_modified,omitempty"`

	// (String) The unique identifier for the file.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The path of the file within the storage zone.
	// The path of the file within the storage zone.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (Number) The size of the file in bytes.
	// The size of the file in bytes.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// (String) The path in the local disk for the file to be uploaded to the storage zone. Use content to define the content directly.
	// The path in the local disk for the file to be uploaded to the storage zone. Use <code>content</code> to define the content directly.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (Number) The ID of the storage zone where the file is stored.
	// The ID of the storage zone where the file is stored.
	Zone *float64 `json:"zone,omitempty" tf:"zone,omitempty"`
}

type FileParameters struct {

	// (String) The to be stored in the file. Use source to upload files from the local disk.
	// The to be stored in the file. Use <code>source</code> to upload files from the local disk.
	// +kubebuilder:validation:Optional
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// (String) Specifies the content type of the file.
	// Specifies the content type of the file.
	// +kubebuilder:validation:Optional
	ContentType *string `json:"contentType,omitempty" tf:"content_type,omitempty"`

	// (String) The path of the file within the storage zone.
	// The path of the file within the storage zone.
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The path in the local disk for the file to be uploaded to the storage zone. Use content to define the content directly.
	// The path in the local disk for the file to be uploaded to the storage zone. Use <code>content</code> to define the content directly.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// (Number) The ID of the storage zone where the file is stored.
	// The ID of the storage zone where the file is stored.
	// +kubebuilder:validation:Optional
	Zone *float64 `json:"zone,omitempty" tf:"zone,omitempty"`
}

// FileSpec defines the desired state of File
type FileSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileInitParameters `json:"initProvider,omitempty"`
}

// FileStatus defines the observed state of File.
type FileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// File is the Schema for the Files API. This resource manages files in a bunny.net storage zone. It is used to upload, update, and delete files within a storage zone.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-bunnynet}
type File struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.path) || (has(self.initProvider) && has(self.initProvider.path))",message="spec.forProvider.path is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   FileSpec   `json:"spec"`
	Status FileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileList contains a list of Files
type FileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []File `json:"items"`
}

// Repository type metadata.
var (
	File_Kind             = "File"
	File_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: File_Kind}.String()
	File_KindAPIVersion   = File_Kind + "." + CRDGroupVersion.String()
	File_GroupVersionKind = CRDGroupVersion.WithKind(File_Kind)
)

func init() {
	SchemeBuilder.Register(&File{}, &FileList{})
}
