// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ContainerImageregistryInitParameters struct {

	// Options: `DockerHub`, `GitHub`
	Registry *string `json:"registry,omitempty" tf:"registry,omitempty"`

	// The token used to authenticate to the registry. If you are importing a resource, declare the token as an empty string.
	TokenSecretRef v1.SecretKeySelector `json:"tokenSecretRef" tf:"-"`

	// The username used to authenticate to the registry.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ContainerImageregistryObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Options: `DockerHub`, `GitHub`
	Registry *string `json:"registry,omitempty" tf:"registry,omitempty"`

	// The username used to authenticate to the registry.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ContainerImageregistryParameters struct {

	// Options: `DockerHub`, `GitHub`
	// +kubebuilder:validation:Optional
	Registry *string `json:"registry,omitempty" tf:"registry,omitempty"`

	// The token used to authenticate to the registry. If you are importing a resource, declare the token as an empty string.
	// +kubebuilder:validation:Optional
	TokenSecretRef v1.SecretKeySelector `json:"tokenSecretRef" tf:"-"`

	// The username used to authenticate to the registry.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ContainerImageregistrySpec defines the desired state of ContainerImageregistry
type ContainerImageregistrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ContainerImageregistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContainerImageregistryInitParameters `json:"initProvider,omitempty"`
}

// ContainerImageregistryStatus defines the observed state of ContainerImageregistry.
type ContainerImageregistryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContainerImageregistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContainerImageregistry is the Schema for the ContainerImageregistrys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-bunnynet}
type ContainerImageregistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.registry) || (has(self.initProvider) && has(self.initProvider.registry))",message="spec.forProvider.registry is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenSecretRef)",message="spec.forProvider.tokenSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ContainerImageregistrySpec   `json:"spec"`
	Status ContainerImageregistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContainerImageregistryList contains a list of ContainerImageregistrys
type ContainerImageregistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContainerImageregistry `json:"items"`
}

// Repository type metadata.
var (
	ContainerImageregistry_Kind             = "ContainerImageregistry"
	ContainerImageregistry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContainerImageregistry_Kind}.String()
	ContainerImageregistry_KindAPIVersion   = ContainerImageregistry_Kind + "." + CRDGroupVersion.String()
	ContainerImageregistry_GroupVersionKind = CRDGroupVersion.WithKind(ContainerImageregistry_Kind)
)

func init() {
	SchemeBuilder.Register(&ContainerImageregistry{}, &ContainerImageregistryList{})
}
